<body style="background-color: #4B515D;">
    <section class="vh-100">
      <div class="container py-5 h-100">
    
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-8 col-lg-6 col-xl-4">
            <h1 style="text-align: center;color:#111122">Weather Forecast</h1>
    
            <?php
            echo $forecast;
            ?>
    
          </div>
        </div>
    
      </div>
    </section>
</body>